// Copyright 2017-2022 @polkadot/wasm-bridge authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/wasm-bridge', path: new URL(import.meta.url).pathname, type: 'deno', version: '6.1.6-2-x' };
